version: '3.8'

services:
  app:
    build: .
    container_name: myapp
    ports:
      - "8443:8443"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/quiz_schema
      - SPRING_DATASOURCE_USERNAME=rmizilin
      - SPRING_DATASOURCE_PASSWORD=Understand7$
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - mynetwork

  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz_schema
      MYSQL_USER: rmizilin
      MYSQL_PASSWORD: Understand7$
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
